# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: mue1-ncrypto-int-ado-vm-ubuntu

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'NonProd App SP'
    KeyVaultName: 'mue1-ncrypto-dev-kv'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: Bash@3
  displayName: Run build
  inputs:
    filePath: './scripts/test.sh'
    arguments: '$(System.DefaultWorkingDirectory) $(Build.ArtifactStagingDirectory) $(buildConfiguration) $(persistence-postgres-host) $(persistence-postgres-user) $(persistence-postgres-password) $(persistence-cosmos-endpointUrl) $(persistence-cosmos-authorizationKey) $(persistence-cosmos-databaseId)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
  env:
    PERSISTENCE_POSTGRES_HOST: $(persistence-postgres-host)