# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: mue1-ncrypto-int-ado-vm-ubuntu

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'NonProd App SP'
    KeyVaultName: 'mue1-ncrypto-dev-kv'
    SecretsFilter: '*'
    RunAsPreJob: true
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update -y && sudo apt-get install -y --no-install-recommends jq
      jq '.persistence.postgres.host="$(persistence-postgres-host)"|.persistence.postgres.user="$(persistence-postgres-user)"|.persistence.postgres.password="$(persistence-postgres-password)"|.persistence.cosmos.endpointUrl="$(persistence-cosmos-endpointUrl)"|.persistence.cosmos.authorizationKey="$(persistence-cosmos-authorizationKey)"|.persistence.cosmos.databaseId="$(persistence-cosmos-databaseId)"' ./src/Miningcore.Integration.Tests/config_test.json > tmp.$$.json && mv tmp.$$.json ./src/Miningcore.Integration.Tests/config_test.json