# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: mue1-ncrypto-int-ado-vm-ubuntu

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'NonProd App SP'
    KeyVaultName: 'mue1-ncrypto-dev-kv'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo '.persistence.postgres.host="$(PERSISTENCE_POSTGRES_HOST)"|.persistence.postgres.user="$PERSISTENCE_POSTGRES_USER"|.persistence.postgres.password="$PERSISTENCE_POSTGRES_PASSWORD"|.persistence.cosmos.endpointUrl="$PERSISTENCE_COSMOS_ENDPOINTURL"|.persistence.cosmos.authorizationKey="$PERSISTENCE_COSMOS_AUTHORIZATIONKEY"|.persistence.cosmos.databaseId="$PERSISTENCE_COSMOS_DATABASEID"'
  env:
    PERSISTENCE_POSTGRES_HOST: $(persistence-postgres-host)
    PERSISTENCE_POSTGRES_USER: $(persistence-postgres-user)
    PERSISTENCE_POSTGRES_PASSWORD: $(persistence-postgres-password)
    PERSISTENCE_COSMOS_ENDPOINTURL: $(persistence-cosmos-endpointUrl)
    PERSISTENCE_COSMOS_AUTHORIZATIONKEY: $(persistence-cosmos-authorizationKey)
    PERSISTENCE_COSMOS_DATABASEID: $(persistence-cosmos-databaseId)
